name: Build LaTeX example

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v4
        with:
          root_file: outline.tex
          working_directory: example
          latexmk_use_xelatex: false
